module.exports = {
  apps: [
    {
      name: "claude-terminal-blue",
      script: "server.js",
      cwd: __dirname,
      env: {
        NODE_ENV: "production",
        HOST: "127.0.0.1",
        PORT: 3000,
        CT_WS_DEBUG: "1",
      },
      autorestart: true,
      max_restarts: 10,
      max_memory_restart: "1200M",
      error_file: "./logs/error-blue.log",
      out_file: "./logs/out-blue.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      watch: false,
      kill_timeout: 45000,
      listen_timeout: 60000,
      wait_ready: true,
    },
    {
      name: "claude-terminal-green",
      script: "server.js",
      cwd: __dirname,
      env: {
        NODE_ENV: "production",
        HOST: "127.0.0.1",
        PORT: 3001,
        CT_WS_DEBUG: "1",
      },
      autorestart: true,
      max_restarts: 10,
      max_memory_restart: "1200M",
      error_file: "./logs/error-green.log",
      out_file: "./logs/out-green.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      watch: false,
      kill_timeout: 45000,
      listen_timeout: 60000,
      wait_ready: true,
    },
  ],
};
